# Generated by Django 6.0.3 on 2026-04-15 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='le nombre de caractere doit etre superieur a deux')])),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='le nombre de caractere doit etre superieur a deux')])),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
