# Generated by Django 6.0.3 on 2026-04-17 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_created=True)),
                ('libele', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message="Le minimun de caractere c'est 2")])),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Le nombre de caractere doit suprerieur a 10')])),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(default=True, upload_to='')),
            ],
        ),
    ]
