# Generated by Django 6.0.3 on 2026-05-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_all_product', 'Can view all product')]},
        ),
    ]
